version: "3.8"
 
services:
  backend:
    build: .
    container_name: flask_backend
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
      - MYSQL_HOST=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=mydatabase
    depends_on:
      - db
    networks:
      - app_network
 
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=mydatabase
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3308:3306"  
    networks:
      - app_network
 
volumes:
  mysql_data:
 
networks:
  app_network:
    driver: bridge