name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_PROD }}

      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 206.189.99.93 >> ~/.ssh/known_hosts

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Create deployment directory
        run: |
          ssh root@206.189.99.93 "mkdir -p /srv/backend2"

      - name: Copy docker-compose file to server
        run: |
          scp docker-compose.prod.yaml root@206.189.99.93:/srv/backend2/docker-compose.yaml

      - name: Stop existing containers
        run: |
          ssh root@206.189.99.93 "cd /srv/backend2 && docker compose down || true"

      - name: Create .env file
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: cesaxis
          MYSQL_DATABASE: cesaxis
          MYSQL_ROOT_PASSWORD: cesaxis
        run: |
          ssh root@206.189.99.93 "cat > /srv/backend2/.env << EOL
          GITHUB_REPOSITORY=${GITHUB_REPOSITORY}
          GITHUB_SHA=${GITHUB_SHA}
          MYSQL_USER=${MYSQL_USER}
          MYSQL_PASSWORD=${MYSQL_PASSWORD}
          MYSQL_DATABASE=${MYSQL_DATABASE}
          MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
          EOL"

      - name: Deploy with new docker-compose
        run: |
          ssh root@206.189.99.93 "cd /srv/backend2 && \
          docker compose pull && \
          docker compose up -d"