name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_PROD }}
      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 188.166.118.113 >> ~/.ssh/known_hosts
      - name: Check out
        uses: actions/checkout@v4
      - name: Create DIR
        run: |
          ssh root@188.166.118.113 "mkdir -p /srv/backend"
      - name: Copy production docker compose
        run: | 
          scp docker-compose.prod.yml root@188.166.118.113:/srv/backend/docker-compose.yml
      - name: Create .env file
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: cesaxis
          MYSQL_DATABASE: cesaxis
          MYSQL_ROOT_PASSWORD: cesaxis
        run: |
          ssh root@188.166.118.113 "cat > /srv/backend2/.env << EOL
          GITHUB_REPOSITORY=${GITHUB_REPOSITORY}
          GITHUB_SHA=${GITHUB_SHA}
          MYSQL_USER=${MYSQL_USER}
          MYSQL_PASSWORD=${MYSQL_PASSWORD}
          MYSQL_DATABASE=${MYSQL_DATABASE}
          MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
          EOL"
        

