name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Build and run containers
        run: |
          docker compose build

      - name: Install dependencies
        run: |
            pip install -r requirements.txt

      - name: Lint with flake8
        continue-on-error: true
        run: |
            flake8 .

      - name: Test with pytest
        continue-on-error: true
        run: |
            python -m pytest
